components:
  main.settings:
    canny_args: !!python/tuple
    - 400
    - 800
    crop: !!python/tuple
    - 0
    - 0
    - 80
    - 80
    min_conf: 0.8
    tap_offset: null
    type: ssim
  map_selected.start:
    crop: !!python/tuple
    - 1120
    - 640
    - 1235
    - 675
    tap_offset: !!python/tuple
    - 0
    - 0
    text: "\u5F00 \u59CB \u884C \u52A8"
    threshold: 150
    type: ocr
geometry: !!python/tuple
- 1280
- 720
pages: {}
