boxes:
  maps.indicators:
    crop: !!python/tuple
    - 0
    - 65
    - 1280
    - 720
    deps: []
    match_th: 0.2
    method: 5
    ssim_th: 0.6
    subimages:
    - maps.three_star_indicator
    - maps.four_star_indicator
    type: subimage
    weights: !!python/tuple
    - 1.0
    - 1.0
    - 1.0
  missions.main_story.chapters:
    canny_args: null
    crop: !!python/tuple
    - 0
    - 80
    - 1280
    - 600
    deps:
    - missions.main_story.selected
    kernel: 5
    ref_color: null
    repeat: null
    shape: !!python/tuple
    - 410
    - 470
    - 20
    - 20
    threshold: 200
    type: float
components:
  back:
    canny_args: null
    crop: !!python/tuple
    - 20
    - 15
    - 140
    - 60
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 70
    - 20
    type: ssim
  battle_finished.title:
    config: null
    crop: !!python/tuple
    - 20
    - 580
    - 420
    - 680
    lang: chi_sim
    tap_offset: !!python/tuple
    - 200
    - 50
    text: "\u884C \u52A8 \u7ED3 \u675F"
    threshold: 200
    type: ocr
  in_battle.take_over:
    canny_args: null
    crop: !!python/tuple
    - 455
    - 625
    - 610
    - 685
    min_conf: 0.8
    tap_offset: null
    type: ssim
  main.missions:
    config: null
    crop: !!python/tuple
    - 900
    - 120
    - 1055
    - 200
    lang: chi_sim
    tap_offset: !!python/tuple
    - 100
    - 40
    text: "\u4F5C \u6218"
    threshold: 200
    type: ocr
  main.settings:
    canny_args: !!python/tuple
    - 400
    - 800
    crop: !!python/tuple
    - 0
    - 0
    - 80
    - 80
    min_conf: 0.8
    tap_offset: null
    type: ssim
  main.tasks:
    config: null
    crop: !!python/tuple
    - 715
    - 555
    - 805
    - 615
    lang: chi_sim
    tap_offset: !!python/tuple
    - 100
    - 40
    text: "\u4EFB \u52A1"
    threshold: 200
    type: ocr
  map_selected.start:
    config: null
    crop: !!python/tuple
    - 1120
    - 640
    - 1235
    - 675
    lang: chi_sim
    tap_offset: !!python/tuple
    - 0
    - 0
    text: "\u5F00 \u59CB \u884C \u52A8"
    threshold: 150
    type: ocr
  menu:
    canny_args: null
    crop: !!python/tuple
    - 165
    - 15
    - 370
    - 60
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 100
    - 20
    type: ssim
  menu.main:
    canny_args: !!python/tuple
    - 50
    - 100
    crop: !!python/tuple
    - 55
    - 230
    - 130
    - 305
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 35
    - 35
    type: ssim
  menu.missions:
    canny_args: null
    crop: !!python/tuple
    - 500
    - 50
    - 560
    - 125
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 30
    - 40
    type: ssim
  missions.main_story.selected:
    canny_args: null
    crop: !!python/tuple
    - 0
    - 600
    - 160
    - 715
    min_conf: 0.8
    tap_offset: null
    type: ssim
  missions.of_r:
    canny_args: null
    crop: !!python/tuple
    - 773
    - 620
    - 911
    - 704
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 60
    - 40
    type: ssim
  missions.of_r.fest:
    canny_args: null
    crop: !!python/tuple
    - 908
    - 383
    - 1192
    - 455
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 140
    - 35
    type: ssim
  missions.of_r.main:
    canny_args: null
    crop: !!python/tuple
    - 930
    - 295
    - 1214
    - 367
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 140
    - 35
    type: ssim
  of_r.maps.obsidian_icon:
    canny_args: null
    crop: !!python/tuple
    - 70
    - 643
    - 145
    - 673
    min_conf: 0.8
    tap_offset: null
    type: ssim
  prepare.start:
    canny_args: null
    crop: !!python/tuple
    - 1040
    - 370
    - 1165
    - 640
    min_conf: 0.8
    tap_offset: !!python/tuple
    - 60
    - 150
    type: ssim
  tasks.got_rewards:
    config: null
    crop: !!python/tuple
    - 580
    - 135
    - 700
    - 175
    lang: chi_sim
    tap_offset: !!python/tuple
    - 60
    - 510
    text: "\u83B7 \u5F97 \u7269 \u8D44"
    threshold: 150
    type: ocr
geometry: !!python/tuple
- 1280
- 720
query_sets:
  map_selected.info:
    deps:
    - map_selected.start
    queries:
    - config: null
      crop: !!python/tuple
      - 810
      - 112
      - 960
      - 149
      lang: chi_sim
      threshold: 200
      type: ocr
    - config: null
      crop: !!python/tuple
      - 880
      - 83
      - 965
      - 108
      lang: eng
      threshold: 200
      type: ocr
    - config: null
      crop: !!python/tuple
      - 1184
      - 677
      - 1228
      - 714
      lang: eng
      threshold: 200
      type: ocr
    - config: null
      crop: !!python/tuple
      - 1120
      - 20
      - 1240
      - 60
      lang: eng
      threshold: 200
      type: ocr
    type: fixed
  maps.map_name:
    box: maps.indicators
    deps: []
    queries:
    - config: null
      crop: !!python/tuple
      - 33
      - 5
      - 118
      - 35
      lang: eng
      threshold: 125
      type: ocr
    - config: null
      crop: !!python/tuple
      - 33
      - 5
      - 145
      - 35
      lang: eng
      threshold: 125
      type: ocr
    - tap_offset: !!python/tuple
      - 80
      - 15
      type: tap
    type: float
  of_r.maps.obsidian_count:
    deps:
    - of_r.maps.obsidian_icon
    queries:
    - config: null
      crop: !!python/tuple
      - 200
      - 648
      - 275
      - 670
      lang: eng
      threshold: 200
      type: ocr
    type: fixed
searches:
  maps.map_entry:
    bound: 20
    deps:
    - menu
    init_swipe: !!python/tuple
    - 50
    - 360
    - 50000
    - 0
    - 1000
    next_swipe: !!python/tuple
    - 1000
    - 360
    - -800
    - 0
    - 2500
    query_set: maps.map_name
